first commit(not final)
sergey-berezin/401_kosmynin pull request #1
Opened 2023-09-28 20:17 UTC by KosmyninStanislav

2023-10-02 10:36 UTC, sergey-berezin requested changes
В PR не включены файлы проекта.

2023-10-02 10:36 UTC, sergey-berezin commented on Bert/Bert.App/Program.cs
> +        while (!token.IsCancellationRequested)
Когда будет установлен cancellation request?

2023-10-02 10:36 UTC, sergey-berezin commented on Bert/Bert.Nuget/BertModelConnection.cs
> +    public async Task<String> ExecuteAsync(string prompt, CancellationToken token)
Этот метод не является асинхронным. Он возвращает управление когда задача уже завершилась.

2023-10-02 10:36 UTC, sergey-berezin commented on Bert/Bert.Nuget/BertModelConnection.cs
> +    public async Task CreateOrDownloadAsync(string url)
В задании требовалось обработать временные ошибки при помощи нескольких повторов.

2023-10-10 15:31 UTC, sergey-berezin requested changes
Появился один новый вопрос, и не отвечены ещё два старых.

2023-10-25 15:58 UTC, KosmyninStanislav commented on Bert/Bert.App/Program.cs
> +        while (!token.IsCancellationRequested)
Исправил

2023-10-25 15:59 UTC, KosmyninStanislav commented on Bert/Bert.Nuget/BertModelConnection.cs
> +        session = new InferenceSession(path);
Исправил, не будет

2023-10-26 08:00 UTC, sergey-berezin commented on Bert/Bert.App/Program.cs
> +                token.ThrowIfCancellationRequested();
Здесь достаточно сделать break. Бросок исключения - это достаточно дорогая операция, тем более, что ловите его вы несколькими строками ниже.

2023-10-26 08:01 UTC, merged